name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: 13.233.132.160
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd /home/ubuntu/smart-campus-management-system-dynamic
            git pull origin main
            sudo systemctl restart smartcampus
